### ISSUE TITLE
'std_show' bug

### ISSUE THREAD

**Issue by denis0706** [evertiro/historical-redux2#64] opened 2013-01-25 14:28 UTC
If $defaults['std_show'] set to true and std is set, it is unable to set some option to empty (for example empty text field, or unchecked checkbox)

**Comment by denis0706** [comment] 2013-02-01 10:17
It doesn't fix the issue, but makes another one.

[if field value is 0](https://github.com/ghost1227/Redux-Framework/blob/master/options/defaults.php#L123)    empty () will return true, so field value will be get with (https://github.com/ghost1227/Redux-Framework/blob/master/options/defaults.php#L123) and set again to std value

**Comment by denis0706** [comment] 2013-02-01 11:08
Another issue that [logical OR is using](https://github.com/ghost1227/Redux-Framework/blob/master/options/defaults.php#L106).
If first condition is false it will continue to check next condition because of using OR and on next condition php will throw notice of undefined index.
Another problem:
get_transient('redux-opts-saved') is used for showing notification on option page and must be only used for this. If some problem occurs and page doesn't load normal after pressing save button (for example php shows some warning/notice/error) this transient won't be deleted because [it is deleted in output](https://github.com/ghost1227/Redux-Framework/blob/master/options/defaults.php#L631). So _std_get() will always return null.

And it is not last problem with  'std_show'  and handling of std values. Another one is that we can use only redux get() method to get option value, because this is the only way to get new fields with std values.

At the end I just want to say that we have a lot of  issues which started after implementing 'std_show' and we always solve it with dirty workarounds. So soon our code will be one big workaround for working std_show 'feature'.

Hope to hear the opinions of other developers on this subject.

**Comment by evertiro** [comment] 2013-02-01 15:26
I've got a new option in mind that should make everyone happy and get rid of the annoying bugs.

**Comment by evertiro** [comment] 2013-02-01 20:02
I've been thinking that perhaps the better way to go about this would be to change the idea altogether... Drop the description line down below the field instead of beside it and add a span that will display 'Default: &lt;mydefault&gt;' or similar if std_show == true. Thoughts?

**Comment by denis0706** [comment] 2013-02-01 22:04
Your idea is that there should be when we hear 'std_show' and it will work well, 
but if I understand you correctly your thoughts do not have common with [signio](https://github.com/ghost1227/Redux-Framework/pull/53), and problems of signo's implimintation - option name does not reveal the meaning of it, not clear how to apply it, and the main - it brings new unclear feature with the inability to use the old methods paying for it at the cost of flexibility.
We may use your suggestion but not in the context of the previous meaning this feature.

**Comment by evertiro** [comment] 2013-02-01 22:09
It's true that my thoughts aren't 100% in line with the previous implementation, but it does achieve a similar functionality in that the user is still informed as to the intended defaults. The problem is that this function has caused an exorbitant number of headaches and, as you previously indicated, patching it over and over has caused the code to get more and more convoluted with each patch. One way or the other, we have to find a solution that will make everyone happy and keep the code clean... and quickly.

**Comment by denis0706** [comment] 2013-02-01 22:17
Agree. Yours functionality is a different interpretation non-core functionality of previous solution, and i like it. So lets wait a little for thoughts from other developers, despite the fact that they are not very active, I hope we will find the right solution soon

**Comment by evertiro** [comment] 2013-02-02 17:35
Other than a minor typo in your code ($default not default), I merged your pull manually so I could break it down a bit (it's now three commits). See if that fixes the issue at least for the moment.

**Comment by signo** [comment] 2013-02-02 17:43
I am going to take a closer look at this issue over the weekend, i'll report monday.

**Comment by evertiro** [comment] 2013-02-02 19:06
Please work on a clean pull from the most recent dev build. Looking forward to seeing what the community can come up with!

**Comment by evertiro** [comment] 2013-02-12 07:50
Any word?

**Comment by evertiro** [comment] 2013-03-25 21:59
signo, are you still working on this or have you abandoned it?

**Closed as completed** 2013-07-13 04:43 UTC
Labels: bug
